name = "karya-yullie-worker"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Secrets are managed via Wrangler CLI
# Use: wrangler secret put TELEGRAM_BOT_TOKEN
# Use: wrangler secret put TELEGRAM_CHAT_ID
